cc_binary(
    name = "stl_algorithm",
    srcs = "stl_algorithm.cc",
)

cc_binary(
    name = "heap_sort",
    srcs = "heap_sort.cc",
)

cc_binary(
    name = "class_test",
    srcs = "class_test.cc",
)

cc_binary(
    name = "float",
    srcs = "float.cc",
)

cc_binary(
    name = "check_end",
    srcs = "check_end.cc",
)

cc_binary(
    name = "inotify",
    srcs = ["inotify.cc",]
)

cc_binary(
    name = "open_test",
    srcs = ["open_test.cc",
    "time_bench.cc",]
)
