cc_test(
    name = "reverse-words-in-string",
    srcs = "reverse-words-in-string.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "reverse-polish-notation",
    srcs = "reverse-polish-notation.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
cc_test(
    name = "max_points_on_line",
    srcs = "max_points_on_line.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
cc_test(
    name = "sort-list",
    srcs = "sort-list.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
