cc_test(
    name = "reverse-words-in-string",
    srcs = "reverse-words-in-string.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "reverse-polish-notation",
    srcs = "reverse-polish-notation.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
cc_test(
    name = "max_points_on_line",
    srcs = "max_points_on_line.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
cc_test(
    name = "sort-list",
    srcs = "sort-list.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
cc_test(
    name = "lru-cache",
    srcs = "lru-cache.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "lru-cache2",
    srcs = "lru-cache2.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "bintree-preorder-traversal",
    srcs = "bintree-preorder-traversal.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "bintree-postorder-traversal",
    srcs = "bintree-postorder-traversal.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )

