cc_test(
    name = "reverse-words-in-string",
    srcs = "reverse-words-in-string.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
  )
cc_test(
    name = "reverse-polish-notation",
    srcs = "reverse-polish-notation.cc",
    deps = [
    "//thirdparty/gtest:gtest_main",
    ],
    )
