cc_test(
    name = "ms1",
    srcs = [
    "ms1.cc",
    ],
)
cc_test(
    name = "ms2",
    srcs = [
    "ms2.cc",
    ],
)
cc_test(
    name = "ms3",
    srcs = [
    "ms3.cc",
    ],
)
cc_test(
    name = "ms4",
    srcs = [
    "ms4.cc",
    ],
)
